import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

// Root Layout
export default function RootLayout({ children }) {
	return (
		<html lang="en" className="p-10">
			<body className={inter.className}>
				<nan className="my-5">
					<ul className="flex gap-10">
						<li>
							<Link href="/">Home</Link>
						</li>
						<li>
							<Link href="/about">About</Link>
						</li>
						<li>
							<Link href="/blog">Blog</Link>
						</li>
						<li>
							<Link href="/posts">Post</Link>
						</li>
					</ul>
				</nan>
				<hr />
				{children}
			</body>
		</html>
	);
}
